[Alerts]
  [Alerts.Apple]
  rule = "from:noreply@email.apple.com"
  [Alerts.Amazon]
  rule = "from:-confirm@amazon.com"
  [Alerts.CircleCI]
  rule = "from:@circleci.com"
  [Alerts.Kickstarter]
  rule = "from:no-reply@kickstarter.com"
  [Alerts.Meetup]
  rule = "from:info@meetup.com"
  [Alerts.Linode]
  rule = "subject:'Linode Alert' or subject:'Linode Events Notification' or from:noreply@linode.com"
  [Alerts.Synology]
  from-or = ["notification@synology.com", "@synologynotification.com"]
  [Alerts.Keybase]
  rule = "from:notify@keybase.io"
  [Alerts.LetsEncrypt]
  rule = "from:expiry@letsencrypt.org"
  [Alerts.UPS]
  rule = "from:mcinfo@ups.com"
  [Alerts.Prey]
  rule = "from:@preyproject.com"
  [Alerts.IFTTT]
  from-or = ["alerts@ifttt.com", "support@ifttt.com"]
  [Alerts.asciinema]
  rule = "from:hello@asciinema.org"
  [Alerts.IndieGoGo]
  rule = "from:noreply@indiegogo.com"
  [Alerts.TurboTax]
  from-or = ["do_not_reply@intuit.com", "turbotax@notification.intuit.com"]
  [Alerts.JetBlue]
  rule = "from:do-not-reply@change.jetblue.com"
  [Alerts.JetBlueCard]
  rule = "from:service@alerts.jetbluemastercard.com"
  [Alerts.Gitter]
  rule = "from:support@gitter.im"
  [Alerts.Taxi]
  rule = "from:donotreply@taxihail.com"
  
[Billing]
  [Billing.Amazon]
  from-or = ["order-update@amazon.com", "noreply@amazon.com"]
  [Billing.Apple]
  from-or = ["orders.apple.com", "donotreply@apple.com", "concierge@insideapple.com", "AMR_Payment_Processing_US@apple.com", "order_change@store.apple.com", "do_not_reply@apple.com"]
  [Billing.ATT]
  from-or = ["'AT&T Customer Care for Wireless'", "att-mail.com"]
  [Billing.BoA]
  from-or = ["onlinebanking@ealerts.bankofamerica.com", "merrilledge@ml.com", "bankofamerica.com"]
  [Billing.Blizzard]
  from-or = ["noreply@em.blizzard.com", "noreply@blizzard.com"]
  [Billing.Github]
  rule = "from:support@github.com or subject:'[GitHub] Payment Receipt' or subject:'[Github] Payment Receipt for samdmarshall'"
  [Billing.Grubhub]
  from-or = ["order@grubhub.com", "orders@eat.grubhub.com"]
  [Billing.iTunesReceipts]
  from-or = ["do_not_reply@itunes.com", "no_reply@email.apple.com"]
  [Billing.JetBlue]
  from-or = ["notifications@jetblue.com", "jetblueairways@email.jetblue.com"]
  [Billing.Linode]
  rule = "from:billing@linode.com"
  [Billing.NameDotCom]
  from-or = ["support@name.com", "noreply@name.com"]
  [Billing.Simple]
  from-or = ["notify@e.simple.com", "support@simple.com", "notify@simple.com"]
  [Billing.PlayStation]
  from-or = ["Sony@email.sonyentertainmentnetwork.com", "PlayStation@playstationemail.com"]
  [Billing.PayPal]
  from-or = ["service@paypal.com", "member@paypal.com", "paypal@paypal.com"]
  [Billing.Patreon]
  rule = "from:bingo@patreon.com"
  [Billing.StudentLoans]
  rule = "from:info@borrowerservices.mygreatlakes.org"
  [Billing.HumbleBundle]
  rule = "from:contact@humblebundle.com or subject:'Your Humble Bundle receipt'"
  [Billing.SquareCash]
  rule = "from:cash@square.com"
  [Billing.Bandcamp]
  rule = "from:noreply@bandcamp.com"
  [Billing.Fidelity]
  from-or = ["Fidelity.Investments.email@workplacedocs.fidelity.com", "Fidelity.Investments@mail.fidelity.com"]
  [Billing.TurboTax]
  rule = "from:TurboTax@e.turbotax.intuit.com"
  [Billing.Subscriptions]
  from-or = ["support@getcloudapp.com", "support@raynersw.com", "support@raynersoftware.com"]
  [Billing.Fangamer]
  rule = "from:orders@fangamer.com"
  [Billing.Gamestop]
  rule = "from:orders@gamestop.com"

[Developer]
  [Developer.Apple]
  from-or = ["noreply-appledev@apple.com", "developer@insideapple.com"]
  [Developer.Github]
  from-or = ["notifications@github.com", "noreply@github.com"]
  rule = "to:@noreply.github.com or cc:mentions@noreply.github.com"
  [Developer.Radar]
  from-or = ["devbugs@apple.com", "dts-bugmail@group.apple.com"]
  [Developer.Seed]
  from-or = ["seedsu@apple.com", "seedx@apple.com"]
  subject-or = ["'AppleSeed'", "'Seed Notice'"]
  [Developer.CodeClimate]
  rule = "from:hello@codeclimate.com"

[MailingList]
from-or = ["security-announce-request@lists.apple.com", "macbeta@list.valvesoftware.com", "product-security-noreply@lists.apple.com", "darwin-dev@lists.apple.com", "AppleTeacher@InsideApple.apple.com", "getmail-help@lists.pyropus.ca", "getmail@lists.pyropus.ca", "@bountysource.com"] 
to-or = ["Women-Who-Code-Boston-list@meetup.com", "darwin-dev@lists.apple.com", "cocoaheadsboston@googlegroups.com", "bug-texinfo@gnu.org", "Women-Who-Code-Boston", "getmail@lists.pyropus.ca"]

[Employment]
  [Employment.MLB]
  from-or = ["@mlb.com", "@bamtechmedia.com", "@disneystreaming.com"]
  [Employment.iRobot]
  rule = "from:@irobot.com"

[Social]
  [Social.Mastodon]
  rule = "from:@awoo.space"

[spam]
from-or = ["happybirthday@movies.fandango.com", "customer-reviews-messages@amazon.com", "store-news@amazon.com", "@marketplace.amazon.com", "recommendations@ifttt.com"]

[sent]
from-or = ["@pewpewthespells.com", "@samdmarshall.com"]

[Charity]
rule = "to:charities@"

[Apartment]
rule = "to:properties@"

[Archive]
rule = "tag:inbox and not date:-1month..today"
