
[Alerts]
  [Alerts.Apple]
  from-or = ["noreply@email.apple.com", "noreply@apple.com"]

  [Alerts.Amazon]
  from-or = ["-confirm@amazon.com", "shipment-tracking@amazon.com"]

  [Alerts.CircleCI]
  from-or = ["@circleci.com"]

  [Alerts.Kickstarter]
  from-or = ["no-reply@kickstarter.com"]

  [Alerts.Meetup]
  from-or = ["info@meetup.com"]

  [Alerts.Linode]
  rule = "subject:'Linode Alert' or subject:'Linode Events Notification' or from:noreply@linode.com"

  [Alerts.Synology]
  from-or = ["notification@synology.com", "@synologynotification.com", "Synology@NAS.local"]

  [Alerts.KeyBase]
  from-or = ["notify@keybase.io"]

  [Alerts.LetsEncrypt]
  from-or = ["expiry@letsencrypt.org", "noreply@letsencrypt.org"]

  [Alerts.UPS]
  from-or = ["mcinfo@ups.com"]

  [Alerts.Prey]
  from-or = ["@preyproject.com"]

  [Alerts.IFTTT]
  from-or = ["alerts@ifttt.com", "support@ifttt.com"]

  [Alerts.asciinema]
  from-or = ["hello@asciinema.org"]

  [Alerts.IndieGoGo]
  from-or = ["noreply@indiegogo.com"]

  [Alerts.TurboTax]
  from-or = ["do_not_reply@intuit.com", "turbotax@notification.intuit.com"]

  [Alerts.JetBlue]
  from-or = ["do-not-reply@change.jetblue.com"]

  [Alerts.JetBlueCard]
  from-or = ["service@alerts.jetbluemastercard.com", "alerts@service.jetbluemastercard.com"]

  [Alerts.Gitter]
  from-or = ["support@gitter.im"]

  [Alerts.Taxi]
  from-or = ["donotreply@taxihail.com"]

  [Alerts.NameDotCom]
  from-or = [":no-reply@name.com"]

  [Alerts.Comcast]
  from-or = ["@alerts.comcast.net"]
  to-or = ["comcast-junk@"]

  [Alerts.Twitter]
  from-or = ["notify@twitter.com"]

  [Alerts.USPS]
  to-or = ["usps@"]

  [Alerts.iHealth]
  to-or = ["ihealth@"]

  [Alerts.Patreon]
  to-or = ["patreon@"]

  [Alerts.Crunchyroll]
  from-or = ["@crunchyroll.com"]

  [Alerts.Goodreads]
  from-or = ["@mail.goodreads.com"]

  [Alerts.PayPal]
  from-or = ["paypal@mail.paypal.com"]


[Billing]
  [Billing.Amazon]
  from-or = ["order-update@amazon.com", "noreply@amazon.com"]

  [Billing.Apple]
  from-or = ["orders.apple.com", "donotreply@apple.com", "concierge@insideapple.com", "AMR_Payment_Processing_US@apple.com", "order_change@store.apple.com", "do_not_reply@apple.com"]

  [Billing.ATT]
  from-or = ["'AT&T Customer Care for Wireless'", "att-mail.com"]

  [Billing.BoA]
  from-or = ["onlinebanking@ealerts.bankofamerica.com", "merrilledge@ml.com", "bankofamerica.com"]

  [Billing.Blizzard]
  from-or = ["noreply@em.blizzard.com", "noreply@blizzard.com"]

  [Billing.Github]
  rule = "from:support@github.com or subject:'[GitHub] Payment Receipt' or subject:'[Github] Payment Receipt for samdmarshall'"

  [Billing.Grubhub]
  from-or = ["order@grubhub.com", "orders@eat.grubhub.com"]

  [Billing.iTunesReceipts]
  from-or = ["do_not_reply@itunes.com", "no_reply@email.apple.com"]

  [Billing.JetBlue]
  from-or = ["notifications@jetblue.com", "jetblueairways@email.jetblue.com"]

  [Billing.Linode]
  from-or = ["billing@linode.com"]

  [Billing.NameDotCom]
  from-or = ["support@name.com", "noreply@name.com"]

  [Billing.Simple]
  from-or = ["notify@e.simple.com", "support@simple.com", "notify@simple.com"]

  [Billing.PlayStation]
  from-or = ["Sony@email.sonyentertainmentnetwork.com", "PlayStation@playstationemail.com"]

  [Billing.PayPal]
  from-or = ["service@paypal.com", "member@paypal.com", "paypal@paypal.com"]

  [Billing.Patreon]
  from-or = ["bingo@patreon.com"]

  [Billing.StudentLoans]
  from-or = ["info@borrowerservices.mygreatlakes.org"]

  [Billing.HumbleBundle]
  rule = "from:contact@humblebundle.com or subject:'Your Humble Bundle receipt'"

  [Billing.SquareCash]
  from-or = ["cash@square.com"]

  [Billing.Bandcamp]
  from-or = ["noreply@bandcamp.com"]

  [Billing.Fidelity]
  from-or = ["Fidelity.Investments.email@workplacedocs.fidelity.com", "Fidelity.Investments@mail.fidelity.com"]

  [Billing.TurboTax]
  from-or = ["TurboTax@e.turbotax.intuit.com"]

  [Billing.Subscriptions]
  from-or = ["support@getcloudapp.com", "support@raynersw.com", "support@raynersoftware.com"]

  [Billing.Fangamer]
  from-or = ["orders@fangamer.com"]

  [Billing.GameStop]
  from-or = ["orders@gamestop.com"]

  [Billing.Redbubble]
  from-or = ["aboutmyorder@redbubble.com"]

  [Billing.Eversource]
  to-or = ["eversource@"]

  [Billing.Lyft]
  from-or = ["@lyftmail.com"]

  [Billing.Instacart]
  from-or = ["orders@instacart.com"]

  [Billing.Peapod]
  to-or = ["peapod@"]

  [Billing.Ringly]
  to-or = ["ringly@"]

  [Billing.The100]
  subject-or = ["Your Resonant Ventures LLC receipt"]

  [Billing.InhousePharmacy]
  from-or = ["customerservices@inhousepharmacy.vu"]

  [Billing.Bonfire]
  from-or = ["bonfire.com"]

  [Billing.Microsoft]
  from-or = ["Microsoft Store", "stremail@microsoft.com"]
  
  [Billing.UPS]

[Developer]
  [Developer.Apple]
  from-or = ["noreply-appledev@apple.com", "developer@insideapple.apple.com"]

  [Developer.Github]
  rule = "from:notifications@github.com or from:noreply@github.com or to:@noreply.github.com or cc:mentions@noreply.github.com"

  [Developer.Radar]
  from-or = ["devbugs@apple.com", "dts-bugmail@group.apple.com"]

  [Developer.Seed]
  rule = "from:seedsu@apple.com or from:seedx@apple.com or subject:'AppleSeed' or subject:'Seed Notice'"

  [Developer.CodeClimate]
  from-or = ["hello@codeclimate.com"]

  [Developer.DependencyCI]
  from-or = ["dependencyci.com"]

[MailingList]
from-or = ["security-announce-request@lists.apple.com", "macbeta@list.valvesoftware.com", "product-security-noreply@lists.apple.com", "darwin-dev@lists.apple.com", "AppleTeacher@InsideApple.apple.com", "getmail-help@lists.pyropus.ca", "getmail@lists.pyropus.ca", "@bountysource.com"]
to-or = ["Women-Who-Code-Boston-list@meetup.com", "darwin-dev@lists.apple.com", "cocoaheadsboston@googlegroups.com", "bug-texinfo@gnu.org", "Women-Who-Code-Boston", "getmail@lists.pyropus.ca"]

[Support]
  [Support.Apple]
  from-or = ["AppleSupport@email.apple.com"]

  [Support.Fastmail]
  from-or = ["support@fastmail.com"]

  [Support.CloudApp]
  from-or = ["support@getcloudapp.com"]

[Employment]
  [Employment.Recruiter]
  [Employment.Microsoft]
  [Employment.iRobot]
  from-or = ["@irobot.com"]
  [Employment.MLB]
  from-or = ["@mlb.com"]
  [Employment.BAMTechMedia]
  from-or = ["@bamtechmedia.com"]
  [Employment.Disney]
  from-or = ["@disney.com", "@disneystreaming.com"]

[Social]
  [Social.Mastodon]
  from-or = ["@awoo.space", "@witches.social"]

[spam]
subject-or = ["SPAM"]
from-or = ["happybirthday@movies.fandango.com", "customer-reviews-messages@amazon.com", "store-news@amazon.com", "@marketplace.amazon.com", "recommendations@ifttt.com", "ello.com"]

[Charity]
to-or = ["charities@"]

[Apartment]
to-or = ["properties@"]

[Moving]
to-or = ["moving@"]

[Medical]
to-or = ["medical@"]
  [Medical.Therapy]
  from-or = ["@therapyportal.com", "@thriveworks.com"]
  subject-or = ["Thriveworks Appointment Confirmation"]
  [Medical.FenwayHealth]
  [Medical.BrighamWomens]

[Games]
  [Games.Blizzard]
  from-or = ["email@em.blizzard.com"]

  [Games.Bungie]
  to-or = ["bungie@"]

  [Games.Destiny2]
  rule = "tag:Games.The100"

  [Games.The100]
  from-or = ["the100@the100.io"]

  [Games.FinalFantasyhXIV]
  to-or = ["ffxiv@"]

  [Games.Nintendo]
  from-or = ["no-reply@accounts.nintendo.com"]

  [Games.Aspyr]
  from-or = ["aspyr.com"]

[Financial]
  [Financial.LincolnInvestments]
  from-or = ["LINCOLN INVESTMENT", "id@proxyvote.com"]

[Comics]
  [Comics.Sparkler]
  to-or = ["sparkler@"]

  [Comics.ChromaticPress]
  from-or = ["@chromaticpress.com"]

[Notes]
from-or = ["notes@"]

[sent]
rule = "(from:@pewpewthespells.com or from:me@samdmarshall.com) and not (tag:Notes or from:notes@)"

[Archive]
rule = "tag:inbox and not date:-1month..today"

