
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-14T20:36:18-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "e64430ae31a99514b4a5c38d6f220ecdbd76b008",
 "version": "4.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
