---
database: ~/.config/storage/secure
encrypt: 
  cmd: "/usr/local/bin/gpg"
  args: ["--armor", "--recipient", "samantha.marshall@mlb.com", "--encrypt"]
decrypt:
  cmd: "/usr/local/bin/gpg"
  args: ["--no-tty", "--quiet", "--decrypt"]
