[database]
path = "~/.config/storage/secure"

[encrypt]
cmd = "/usr/bin/gpg2"
args = ["--armor", "--recipient", "me@samdmarshall.com", "--encrypt"]

[decrypt]
cmd = "/usr/bin/gpg2"
args = ["--no-tty", "--quiet", "--decrypt"]
