[database]
path = "~/.config/storage/secure"

[encrypt]
cmd = "/usr/local/bin/gpg2"
args = ["--armor", "--recipient", "me@samdmarshall.com", "--encrypt"]

[decrypt]
cmd = "/usr/local/bin/gpg"	
args = ["--no-tty", "--quiet", "--decrypt"]
