#!/usr/bin/env bash
export NOTMUCH_CONFIG="/home/demi/.config/notmuch/notmuch-config"

pushd /home/demi/eMail-backup/
timestamp=`date "+%s"`
output_path="$timestamp.gz"
/usr/bin/notmuch dump --gzip --output="$output_path"

backup_files=`ls .`
for backup in $backup_files ; do
    extension="${backup##*.}"
    filename="${backup%.*}"

    backup_age=`echo "$timestamp - $filename" | bc`
    if [[ $backup_age -gt 86400 ]]; then
        rm "$backup"
    fi
done

popd
