#!/usr/bin/env sh

if [ "$#" -ne 1 ]; then
	echo "usage: dump-plist <path to binary>"
	exit 1
fi

if [[ ! -e $1 ]]; then
	echo "file does not exist"
	exit 1
fi

file_type=`file $1 | grep "Mach-O"`
if [[ ! "$file_type" ]]; then
	echo "Not a Mach-O binary"
	exit 1
fi

otool -X -s __TEXT __info_plist $1 | xxd -r
