#!/usr/bin/env fish
set -l arguments $argv
string match --quiet $arguments[1] (grimoire --list)
set -l use_grimoire (test $status -eq 0)

set -l command $arguments
if $use_grimoire
    set command "grimoire "+ %$arguments
end

while true
    eval $command
    wait
end
