#!/usr/bin/env fish
set -l arguments $argv
set -l use_grimoire false

for entry in (grimoire --list)
	if test entry = arguments[1]
		set use_grimoire true
		break
	end
end

set -l command $arguments
if test $use_grimoire
    set command "grimoire $arguments"
end

while true
    eval $command
    wait
end
