#!/usr/bin/env bash

export NOTMUCH_CONFIG="/Users/Samantha/.config/notmuch/notmuch-config"



# Tags that get filed under "Alerts" 
/usr/local/bin/notmuch tag +Alerts +Alerts.Apple -- from:noreply@email.apple.com
/usr/local/bin/notmuch tag +Alerts +Alerts.Amazon -- from:-confirm@amazon.com
/usr/local/bin/notmuch tag +Alerts +Alerts.CircleCI -- from:@circleci.com
/usr/local/bin/notmuch tag +Alerts +Alerts.Kickstarter -- from:no-reply@kickstarter.com
/usr/local/bin/notmuch tag +Alerts +Alerts.Meetup -- from:info@meetup.com
/usr/local/bin/notmuch tag +Alerts +Alerts.Linode -- subject:"Linode Alert" or subject:"Linode Events Notification"
/usr/local/bin/notmuch tag +Alerts +Alerts.Synology -- from:notification@synology.com or from:@synologynotification.com
/usr/local/bin/notmuch tag +Alerts +Alerts.KeyBase -- from:notify@keybase.io
/usr/local/bin/notmuch tag +Alerts +Alerts.LetsEncrypt -- from:expiry@letsencrypt.org
/usr/local/bin/notmuch tag +Alerts +Alerts.UPS -- from:mcinfo@ups.com
/usr/local/bin/notmuch tag +Alerts +Alerts.Prey -- from:@preyproject.com
/usr/local/bin/notmuch tag +Alerts +Alerts.IFTTT -- from:alerts@ifttt.com or from:support@ifttt.com
/usr/local/bin/notmuch tag +Alerts +Alerts.asciinema -- from:hello@asciinema.org
/usr/local/bin/notmuch tag +Alerts +Alerts.IndieGoGo -- from:noreply@indiegogo.com

# Tags that fet filed under "Billing"
/usr/local/bin/notmuch tag +Billing +Billing.Amazon -- from:order-update@amazon.com or from:noreply@amazon.com
/usr/local/bin/notmuch tag +Billing +Billing.Apple -- from:orders.apple.com or from:donotreply@apple.com or from:concierge@insideapple.com or from:AMR_Payment_Processing_US@apple.com or from:order_change@store.apple.com or from:do_not_reply@apple.com
/usr/local/bin/notmuch tag +Billing +Billing.ATT -- from:"AT&T Customer Care for Wireless"
/usr/local/bin/notmuch tag +Billing +Billing.BoA -- from:onlinebanking@ealerts.bankofamerica.com or from:merrilledge@ml.com or from:bankofamerica.com
/usr/local/bin/notmuch tag +Billing +Billing.Blizzard -- from:noreply@em.blizzard.com or from:noreply@blizzard.com
/usr/local/bin/notmuch tag +Billing +Billing.Github -- from:support@github.com or subject:"[GitHub] Payment Receipt" or subject:"[Github] Payment Receipt for samdmarshall"
/usr/local/bin/notmuch tag +Billing +Billing.Grubhub -- from:order@grubhub.com or from:orders@eat.grubhub.com
/usr/local/bin/notmuch tag +Billing +Billing.iTunesReceipts -- from:do_not_reply@itunes.com or from:"iTunes Store" or from:no_reply@email.apple.com
/usr/local/bin/notmuch tag +Billing +Billing.JetBlue -- from:notifications@jetblue.com or from:jetblueairways@email.jetblue.com
/usr/local/bin/notmuch tag +Billing +Billing.Linode -- from:billing@linode.com
/usr/local/bin/notmuch tag +Billing +Billing.NameDotCom -- from:support@name.com or from:noreply@name.com
/usr/local/bin/notmuch tag +Billing +Billing.Simple -- from:notify@e.simple.com or from:support@simple.com or from:notify@simple.com
/usr/local/bin/notmuch tag +Billing +Billing.PlayStation -- from:Sony@email.sonyentertainmentnetwork.com or from:PlayStation@playstationemail.com
/usr/local/bin/notmuch tag +Billing +Billing.PayPal -- from:service@paypal.com or from:member@paypal.com or from:paypal@paypal.com
/usr/local/bin/notmuch tag +Billing +Billing.Patreon -- from:bingo@patreon.com
/usr/local/bin/notmuch tag +Billing +Billing.StudentLoans -- from:info@borrowerservices.mygreatlakes.org
/usr/local/bin/notmuch tag +Billing +Billing.HumbleBundle -- from:contact@humblebundle.com or subject:"Your Humble Bundle receipt"
/usr/local/bin/notmuch tag +Billing +Billing.SquareCash -- from:cash@square.com
/usr/local/bin/notmuch tag +Billing +Billing.Bandcamp -- from:noreply@bandcamp.com
/usr/local/bin/notmuch tag +Billing +Billing.Fidelity -- from:Fidelity.Investments.email@workplacedocs.fidelity.com or from:Fidelity.Investments@mail.fidelity.com
/usr/local/bin/notmuch tag +Billing +Billing.TurboTax -- from:TurboTax@e.turbotax.intuit.com
/usr/local/bin/notmuch tag +Billing +Billing.Subscriptions -- from:support@getcloudapp.com
/usr/local/bin/notmuch tag +Billing +Billing.Subscriptions -- from:support@raynersw.com or from:support@raynersoftware.com
/usr/local/bin/notmuch tag +Billing +Billing.Fangamer -- from:orders@fangamer.com

# Tags that file under "Developer"
/usr/local/bin/notmuch tag +Developer +Developer.Apple -- from:noreply-appledev@apple.com or from:developer@insideapple.com
/usr/local/bin/notmuch tag +Developer +Developer.Github -- from:notifications@github.com or from:noreply@github.com or to:@noreply.github.com or cc:mentions@noreply.github.com
/usr/local/bin/notmuch tag +Developer +Developer.Radar -- from:devbugs@apple.com or from:dts-bugmail@group.apple.com
/usr/local/bin/notmuch tag +Developer +Developer.Seed -- from:seedsu@apple.com or from:seedx@apple.com or subject:"AppleSeed" or subject:"Seed Notice"
/usr/local/bin/notmuch tag +Developer +Developer.CodeClimate -- from:hello@codeclimate.com

# Various mailing lists
/usr/local/bin/notmuch tag +MailingList -- from:security-announce-request@lists.apple.com
/usr/local/bin/notmuch tag +MailingList -- from:macbeta@list.valvesoftware.com
/usr/local/bin/notmuch tag +MailingList -- from:product-security-noreply@lists.apple.com
/usr/local/bin/notmuch tag +MailingList -- from:darwin-dev@lists.apple.com
/usr/local/bin/notmuch tag +MailingList -- to:Women-Who-Code-Boston-list@meetup.com
/usr/local/bin/notmuch tag +MailingList -- to:darwin-dev@lists.apple.com
/usr/local/bin/notmuch tag +MailingList -- to:cocoaheadsboston@googlegroups.com
/usr/local/bin/notmuch tag +MailingList -- to:bug-texinfo@gnu.org
/usr/local/bin/notmuch tag +MailingList -- to:Women-Who-Code-Boston
/usr/local/bin/notmuch tag +MailingList -- from:AppleTeacher@InsideApple.apple.com

# Tags about employment
/usr/local/bin/notmuch tag +Employment -- tag:Employment.iRobot

# Things that don't go under "Inbox"
/usr/local/bin/notmuch tag +Archive -- tag:inbox and not date:-1month..today
/usr/local/bin/notmuch tag -inbox -- tag:Alerts
/usr/local/bin/notmuch tag -inbox -- tag:Billing
/usr/local/bin/notmuch tag -inbox -- tag:Developer
/usr/local/bin/notmuch tag -inbox -- tag:MailingList
/usr/local/bin/notmuch tag -inbox -- tag:Archive
/usr/local/bin/notmuch tag -inbox -- tag:Employment

# garbage
/usr/local/bin/notmuch tag +spam -- subject:SPAM
/usr/local/bin/notmuch tag +spam -- from:happybirthday@movies.fandango.com
/usr/local/bin/notmuch tag +spam -- from:customer-reviews-messages@amazon.com
/usr/local/bin/notmuch tag +spam -- from:store-news@amazon.com
/usr/local/bin/notmuch tag +spam -- from:@marketplace.amazon.com
/usr/local/bin/notmuch tag +spam -- from:recommendations@ifttt.com

/usr/local/bin/notmuch tag -inbox -unread -- tag:deleted or tag:spam

