#!/usr/bin/env fish

if test (count $argv) -eq 2
    set search_path $argv[2]
else
    set search_path "."
end

if test (count $argv) -ge 1
    set search_string $argv[1]
else
    set search_string ""
end

pt -l $search_string $search_path | fzf
