#!/usr/bin/env fish

set -l temp_file (mktemp --suffix ".html")

goaccess --no-global-config --log-file $argv[1] --real-os --output="$temp_file" # --std-geoip --geoip-database /usr/local/var/GeoIP/GeoIP.dat

command open -a Safari $temp_file
