#!/usr/bin/env fish

set -l temp_file (mktemp --suffix ".html")

goaccess --no-global-config --log-file $argv[1] --geoip-database /usr/local/var/GeoIP/GeoIP.dat --std-geoip --real-os --output="$temp_file"

command open -a Safari $temp_file
