---
database: ~/.config/storage/secure
encrypt_cmd: "gpg --output {output} --recipient samantha.marshall@mlb.com --encrypt {input}"
decrypt_cmd: "gpg --no-tty --quiet --output {output} --decrypt {input}"
