---
database: ~/.config/storage/secure
encrypt_cmd: "gpg --output {output} --armor --recipient me@samdmarshall.com --encrypt {input}"
decrypt_cmd: "gpg --no-tty --quiet --output {output} --decrypt {input}"
